# Generated by Django 5.1.4 on 2026-01-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=160)),
                ('manufacturing_year', models.IntegerField()),
                ('fipe_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
